# Generated by Django 5.2.5 on 2025-08-06 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This product name already exists.'}, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^\\S.*$', 'The name cannot begin with a space.', code='invalid_name'), django.core.validators.MinLengthValidator(3)])),
                ('status', models.CharField(choices=[('in-stock', 'In-Stock'), ('out-of-stock', 'Out-of-stock'), ('preorder', 'Preorder'), ('lowstock', 'Lowstock')], default='in-stock', verbose_name=12)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
